# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Dream.destroy_all
Interpret.destroy_all

#############################################
#############################################
################## Dreams ###################
#############################################
#############################################
 dream1 = Dream.create(location: "Queens, NY", year: "2020", story: "Sometime in February, when I was at work, we were talking about the elections with my boss and one of the Caucasian lawyers that was there.  I asked both of them who they are interested in voting for and my boss wasn't sure yet but he said most likely Biden.  Then the lawyer said how he is actually endorsing Andrew Yang.  I then said, 'Oh yeah, the Asian guy.'  He makes a screwed up face like my response confused him.  He then says to me, 'Do you know how offensive that is? What if I said, 'Oh yeah that Black girl who works reception.'  I was confused and stunned by the statement he said to me because he said it as if I don't know I'm Black and I would be highly offended over someone saying that.  Two, since he is a white man, he wouldn't even know what it's like to walk in my shoes as a Black, young woman.  I was just shocked and disgusted by his comment.")

 dream2 = Dream.create(location: "Queens, NY", year: "2020", story: "While I was looking for apartments, I went with my father and the landlord was a Jewish, white man.  He didn't even want to greet us when we came.  We had to wait for the realtor.  When the realtor showed us around, he just stood there and followed us carefully.  He has a dismissive demeanor and we had liked the place a lot and told the realtor we really wanted the apartment.  We contacted the realtor many times and never heard back.  My father said it right after we left he didn't think we were going to get the place.")

 dream3 = Dream.create(location: "Brooklyn, NY", year: "2020", story: "I was once shopping in a department store in the makeup section and I was walking around the area looking for an item I wanted to purchase.  Suddenly, I noticed two of the white saleswomen following me around the area and looking at me suspiciously.  Normally a salesperson would ask a customer if they need help finding something or any assistance. But these sales women persisted in following me around and surveilling me and offered no help.  After recognizing this behavior, I asked them if there was an issue and if they wanted to help me instead of following me.  A few seconds later a white women walks into the smae makeup section as me and the same saleswomen flocked to the woman and asked if she needed any help.  In that moment, as a Black woman, I immediatley understood what took place.  After that I left the store because there's absolutely no reason for me to remain in a space where I am being watched and surveilled as if I was a theif and I would never spend my money in a place where I am treated as so.")

 dream4 = Dream.create(location: "Queens, NY", year: "2010", story: "Growing up in a predominantly Jewish neighborhood, I face discrimination at a very young age.  I had alot of friends growing up who were Jewish and around 10/11 years old, I know we looked different but I ddidn't think it mattered.  Until one day, there was this new spod around our neighborhood called the Bukharian Teen Lounge.  Contrary to its name, this basement lounge funded by the community focused directly on Bukharian Jews and was open to the public.  Just not for Blacks, I remember being with all my Jewish/White friends and they all decided to go to the lounge.  They all just looked at me with this awkward start yelling, 'So where are you heading?'  This happened all Summer 2010.  The I knew.  I was different.  I didn't feel equal and at 10/11 years old, I came face to face that I will be treated differently for the rest of my life because of the color of my skin.")

 p "#{Dream.count} dream(s) out of 4 dreams created"

#############################################
#############################################
############# Interpret - Food ##############
#############################################
#############################################
symphonyPotatoChips = Interpret.create(name: "Symphony Potato Chips", image_url: "https://i.imgur.com/s6yh1pG.png", website_url: "https://symphonychips.com/", description: "We began as a spice company! My dad Andre' Anderson is a retired Chef that worked on the famous Las Vegas Strip. While on the strip, he developed a custom blend that was sought after by patrons and fellow chefs alike. So naturally, when I tried it I was blown away! So much so that I convinced my dad that we needed to package and sell this ASAP! However, once we were featured in a grocery store we quickly learned that no one buys spices they cannot taste, no matter how pretty the package. So we begin doing in-store demonstrations! We started out by putting the spice on raw vegetables and popcorn. But it wasn't until we began putting it on homemade potato chips in the store did people begin to take notice. The feedback was the same, 'The spices are good, BUT WHERE CAN I GET A BAG OF THESE CHIPS!' So we had to listen to our customers and that's how Symphony Chips was born!", tag: "Food")

mayasCookies = Interpret.create(name: "Maya's Cookies", image_url: "https://i.imgur.com/wxxWdYm.jpg",  website_url: "https://www.mayascookies.com/", description: " Maya's cookies are so delicious because I use only the finest organic, premium whole food ingredients. These cookies are made in small batches and mixed by hand for a genuine homemade taste. I am proud to say that Maya's Cookies are 100% plant based, dairy free and cruelty free.  You are going to LOVE them!", tag: "Food")

projectPop = Interpret.create(name: "Project Pop", image_url: "https://i.imgur.com/4E20ylw.jpg", website_url: "https://www.eatprojectpop.com/", description: "A wild idea turned into a batch of popcorn. A batch of popcorn turned into a passion.  Shortly thereafter, all roads led to every batch of my signature Kettle Popcorn featuring ingredients that were organic, non-GMO, vegan and super easy to pronounce.  Project Pop is on a mission to give the gift of quality snacks, food education and smiles to snackers all over the globe.", tag: "Food")

veganSmart = Interpret.create(name: "Vegan Smart", image_url: "https://i.imgur.com/AoXUQmH.png", website_url: "https://www.vegansmart.com/", description: "In 2002, Kareem and Claude moved to Los Angeles. They immediately recognized the child obesity crisis and decided it was finally time to do something. They founded Healthy Body Products, a healthy vending machine company with the mission of providing healthier options to public schools. Within a year of moving to LA, they co-led a movement that resulted in a ban on junk food in the Los Angeles public schools. Within two years, they were awarded the contract for every public high school and middle school in Los Angeles. Their work garnered them an invitation from President Clinton and Governor Huckabee to visit their foundation and discuss their success in LA in hopes of rolling the ban out nationwide.", tag: "Food")

hellaNuts = Interpret.create(name: "Hella Nuts", image_url: "https://i.imgur.com/DatLUq6.jpg", website_url: "https://thatshellanuts.com/", description: "Hella Nuts™ patent-pending nut meat resembles ground meat. It can be used for tacos, pasta, plant-based burgers, shepards pie, pizzas, burrittos, stuffed bell peppers and an array of other dishes.", tag: "Food")

fineappleVegan = Interpret.create(name: "Fineapplevegan", image_url: "https://i.imgur.com/hxdlONj.png", website_url: "https://fineapplevegan.com/", description: "I find that people often connect through the enjoyment of food. So why not use ridiculously delicious, healthy and cruelty free food to do just that?! Not only do I want to bring people together, but my MAIN focus is to also show them that being vegan doesn't mean you have to sacrifice FLAVOR nor does it mean you have to eat grass all day. I put my EVERYTHING into each and every dish that I prepare. I spend hours, if not days, to perfect each spice, flavor, texture until I get it right. This is more than just vegan food. This is a lifestyle. Whether you're already vegan or a curious carnivore, all are welcome! I promise, you won't regret using one of my BOMB recipes for your 'Meatless Monday' meals!", tag: "Food")

tubbysTaste = Interpret.create(name: "Tubby's Taste", image_url: "https://i.imgur.com/1CnJn6v.png", website_url: "https://www.tubbystaste.com/", description: "Tubby’s Taste is a vegan cookie company inspired by our Founder’s Jamaican-American Roots", tag: "Food")


p "#{Interpret.count} interpret(s) out of 7 foods created"

#############################################
#############################################
############# Interpret - Beauty ############
#############################################
#############################################
sachaCosmetics = Interpret.create(name: "Sacha Cosmetics", image_url: "https://i.imgur.com/wGf2TvO.png", website_url: "https://www.sachacosmetics.com", description: "“Sacha Cosmetics began operations in 1979 in Trinidad and Tobago which is an ethnically diverse market. Our vision was to develop a brand of makeup that all our women, regardless of ancestry, could wear. Today, through innovation and continuous improvement, we believe that SACHA is the most advanced brand of makeup ever developed for multicultural women – Asian, Hispanic, African, American, Indian and other women of color.  It is also an ideal brand for makeup artists who are usually called upon to work on clients with diverse complexions. Since our products work equally well on light, medium and dark skin tones, it is different from and superior to every other makeup line.", tag: "Beauty")

maryLouiseCosmetics = Interpret.create(name: "Mary Louise Cosmetics", image_url: "https://i.imgur.com/cZIrV4y.png", website_url: "https://www.mymarylouise.com", description: "At Mary Louise Cosmetics, we believe that everyone should have easy access to wholesome, natural, and organic beauty products. My grandmothers Mary (maternal), and Louise (paternal) always used natural recipes and homemade remedies in their everyday routines. Mary and Louise continually inspire what our brand stands for, and how we source our ingredients.", tag: "Beauty")

vernonFrancois = Interpret.create(name: "Vernon Francois", image_url: "https://i.imgur.com/YCsDG4p.png", website_url: "https://www.vernonfrancois.com/", description: "The VERNON FRANÇOIS collection will leave the world in a better place than how we found it and improve lives, whilst creating outstanding products for textured hair. In Africa, where our oils are sourced, we work with an organisation which works with local farmers that trades with them fairly. The natural oils that we use are the highest quality, Fair Trade, organic and ethically harvested. Our products are free from parabens, sulfates, phthalates, cruelty, gluten, DEA and dye.", tag: "Beauty")

patternByTraceeEllisRoss = Interpret.create(name: "Pattern by Tracee Ellis Ross", image_url: "https://i.imgur.com/gjW8NUp.png", website_url: "https://patternbeauty.com/", description: "PATTERN focuses on hair health & encourages each hair texture to take up as much space as it desires. Don’t feel the need to 'tame', 'control' or 'stifle' your curls & coils. Let them free. We hope to expand how we communicate, care for & celebrate our hair. We want to reimagine the language we use about our beloved curls & community. Our texture is natural. It is us. And it is beautiful.", tag: "Beauty")

blkAndGrn = Interpret.create(name: "BLK + GRN", image_url: "https://i.imgur.com/tWE5sJd.png", website_url: "https://blkgrn.com/ ", description: "At BLK + GRN, our all Black artisans are carefully chosen by Black health experts who know what an all-natural product truly looks like. We've seen firsthand the damaging effects harmful ingredients and practices have had on our community. Our marketplace connects Black people with natural lifestyles to high-quality, toxic-free brands that share in our mission of health, wellness and community cultivation. We promise to maintain that connection by curating, crafting and consuming consciously for you.", tag: "Beauty")

theLipBar = Interpret.create(name: "The Lip Bar", image_url: "https://i.imgur.com/N8UYGpf.png", website_url: "https://www.thelipbar.com", description: "The Lip Bar is a vegan and cruelty-free beauty brand that exists to help change the way you think about beauty.  Every day people are being told how to be beautiful - so we’re here to remind you that you don’t have to change. You Are Enough!", tag: "Beauty")

bevel = Interpret.create(name: "Bevel", image_url: "https://i.imgur.com/h27ZfYx.png", website_url: "https://www.getbevel.com", description: "Created for men of color with sensitive skin, Bevel has all the grooming necessities you need to keep beards and hairlines in tip-top shape.", tag: "Beauty")

blackGirlSunscreen = Interpret.create(name: "Black Girl Sunscreen", image_url: "https://i.imgur.com/ii9TdjW.png", website_url: "https://www.blackgirlsunscreen.com", description: "Our story begins with the need for melanin women to have a sunscreen brand that caters exclusively to them.  From carrying expensive umbrellas to the beach and downright neglecting to go outside all together, our founder thought it was time to create a natural non-white residue sunscreen brand for women of color.  2016 was the year Black Girl Sun Screen was created in the ever-popular city of Miami, Florida. Beach days are always necessary but blotchy makeup and white residue are two things we were frustrated with when enjoying a sunny day.  In fact, all outside activities began to come to a halt since we knew how much sun rays would damage the skin. (even ours)", tag: "Beauty")

beautyBakerie = Interpret.create(name: "Beauty Bakerie", image_url: "https://i.imgur.com/dAy1T7E.png", website_url: "https://www.beautybakerie.com", description: "Our mission is to be sweet and sweeten the lives of others. We are committed to encouraging men and women to feel both empowered and beautiful. Beauty Bakerie is a direct reflection of my perseverance and passion for great quality products that enhance the beauty in everyone, every day.", tag: "Beauty")

baseButter = Interpret.create(name: "Base Butter", image_url: "https://i.imgur.com/RQaapbx.png", website_url: "https://www.basebutter.com", description: "Creators of the #1 Aloe vera gel based moisturizer for PH balanced and hydrated skin. 4.9 out of 5 stars reviews, cruelty free, and women + black owned.  Our vision is a world where: the depth, breadth and uniqueness of complexion is celebrated; Our skin is acknowledged for where we’ve been and recognized as the amour for where we’re going; At the crossroads of both, we can finally feel comfort wearing, rocking and leading with the skin we’re in.", tag: "Beauty")

theHoneyPotCompany = Interpret.create(name: "The Honey Pot Company", image_url: "https://i.imgur.com/0J5ZhCE.png", website_url: "https://www.thehoneypot.com", description: "The first complete feminine care system that cleanses, protects, and balances your vagina.  Powered by herbs. Made by women. 100% natural.", tag: "Beauty")


p "#{Interpret.count} interpret(s) out of 11 beauty created"

#############################################
#############################################
############# Interpret - Fashion  ##########
#############################################
#############################################

harperimanDolls = Interpret.create(name: "Harperiman Dolls", image_url: "https://i.imgur.com/TDrSsjG.jpg", website_url: "https://www.harperiman.com", description: "Collection of handmade, one-of-a-kind, ethnic dolls.", tag: "Fashion")


zouXou = Interpret.create(name: "Zou Xou", image_url: "https://i.imgur.com/GtZZgIv.png", website_url: "https://www.zouxou.com/", description: "Xou aims to create a shoe wardrobe of modern essentials that are well-made, unfussy, and minimal.  The collection is a narrative of elegant and simple designs made visible through refined contours, subtle detailing, and exceptional quality.The shoes are handcrafted by Argentinian shoemakers using age old techniques and premium leathers. Produced in small quantities, the shoes are made to last and reduce waste and energy as part of responsible manufacturing practices in the slow fashion movement.  Imbued with style and versatility, the shoes exude effortless sophistication with understated confidence. From the moment a woman leaves her house to the moment she returns, the shoes can be worn with ease.", tag: "Fashion")

aliyaWanek = Interpret.create(name: "Aliya Wanek", image_url: "https://i.imgur.com/qivhKJl.png", website_url: "https://www.aliyawanek.com", description: "Founded in 2016, ALIYA WANEK is an eponymous womenswear label that focuses on exploring the connection between one’s identity and style. Our mission is to create comfortable, stylish clothing ethically and sustainably as an extension of the wearer’s individuality. If not sewing the garments herself, Aliya works with a production sewer and other local contractors in the Bay Area to produce and dye her garments, always taking into consideration ways to reduce the brand’s environmental impact.", tag: "Fashion")

beadsByaree = Interpret.create(name: "Beads Byaree", image_url: "https://www.beadsbyaree.com", website_url: "https://i.imgur.com/Lx6Nt56.png", description: "Byaree is an innovative hand crafted jewelry line. All Beads Byaree pieces a created out of the whimsy of designer Areeayl Goodwin's imagination.  Areeayl enjoys creating pieces in real life that have only been in her dreams. Therefore, she's literally making her dreams a reality. Areeayl encourages her supporters and the world to do the same. Areeayl was born and raised in Philadelphia PA, graduated from Howard University in Washington DC with a B.F.A in Acting and now resides in beautiful Brooklyn, NY.", tag: "Fashion")


p "#{Interpret.count} interpret(s) out of 4 fashion created"

#############################################
#############################################
############# Interpret - Tech  #############
#############################################
#############################################

abiliLife = Interpret.create(name: "AbiliLife", image_url: "https://i.imgur.com/Ah9uRiV.png", website_url: "https://www.abililife.com/", description: "AbiliLife engineers products to improve the quality of life for neuromuscular and elderly patients. Courtney Williamson, Ph.D. CEO and Founder, has personal experience with neuromuscular diseases as she was a caregiver for her mother who had Parkinson's disease for 25 years.  Courtney's developed the concept for the Calibrace+ while pursuing doctoral studies at Carnegie Mellon University.", tag: "Tech")

blackGirlsCode = Interpret.create(name: "Black Girls Code", image_url: "https://i.imgur.com/ICsa1xx.png", website_url: "https://www.blackgirlscode.com/ ", description: "To increase the number of women of color in the digital space by empowering girls of color ages 7 to 17 to become innovators in STEM fields, leaders in their communities, and builders of their own futures through exposure to computer science and technology. To provide African-American youth with the skills to occupy some of the 1.4 million computing job openings expected to be available in the U.S. by 2020, and to train 1 million girls by 2040.", tag: "Tech")

johnsonBatteryTechnologies = Interpret.create(name: "Johnson Battery Technologies", image_url: "https://i.imgur.com/mqM96JL.png", website_url: "https://www.johnsonbatterytech.com/", description: "Engineer and serial inventor Lonnie Johnson once disrupted summer vacations and pool parties forever when he invented the Super Soaker. But these days he has his sights set on a more ambitious goal. His newest company, Johnson Battery Technologies (JBT), is developing ceramic, solid-state battery technology designed to outperform lithium-ion batteries in terms of size, capacity, and lifespan. JBT says its batteries are also safer than lithium-ion due to the use of glass electrolytes instead of liquid electrolytes and are able to withstand temperatures up to 300 degrees Fahrenheit . JBT is currently engaging companies in the oil and gas, automotive, and medical device industries to bring products utilizing its battery technology to market. -Design News", tag: "Tech")

devColor = Interpret.create(name: "/dev/color", image_url: "https://i.imgur.com/AzEwpMV.png", website_url: "https://www.devcolor.org/", description: "Black software engineers have historically faced challenges in reaching their full potential. We ensure Black engineers fulfill the promise of their talents, transform the industry, and use their resulting skills and position to give back to their communities.", tag: "Tech")

code2040 = Interpret.create(name: "Code2040", image_url: "https://i.imgur.com/Bb5U99r.png", website_url: "http://www.code2040.org/", description: "Our mission is to activate, connect, and mobilize the largest racial equity community in tech to dismantle the structural barriers that prevent the full participation and leadership of Black and Latinx people in the innovation economy.", tag: "Tech")

blackFemalFoundersEmpire = Interpret.create(name: "Black Female Founders Empire", image_url: "https://i.imgur.com/nPQL7Jj.png", website_url: "https://www.blackfemalefounders.org/", description: "Our mission is to provide awareness, promotion, support and resources for Black women led tech-based* and tech-enabled* startups throughout the U.S. and Black Diaspora.", tag: "Tech")

p "#{Interpret.count} interpret(s) out of 6 tech created"


#############################################
#############################################
############# Interpret - Podcasts  #########
#############################################
#############################################
podcast1619 = Interpret.create(name: "1619", image_url: "https://i.imgur.com/C4tgkyb.jpgA", website_url: "https://www.nytimes.com/2020/01/23/podcasts/1619-podcast.html", description: "New York Times audio series, hosted by Nikole Hannah-Jones, on how slavery has transformed America, connecting past and present through the oldest form of storytelling & examines the long shadow of American slavery. ", tag: "Podcast")

aboutRace = Interpret.create(name: "About Race", image_url: "https://i.imgur.com/XlhgjQt.png", website_url: "https://www.aboutracepodcast.com/", description: "Featuring key voices from the last few decades of anti-racist activism, About Race with Reni Eddo-Lodge looks at the recent history that lead to the politics of today.", tag: "Podcast")

codeSwitch = Interpret.create(name: "Code Switch", image_url: "Code Switch", website_url: "https://www.npr.org/podcasts/510312/codeswitch", description: "It's the fearless conversations about race that you've been waiting for! Hosted by journalists of color, our podcast tackles the subject of race head-on. We explore how it impacts every part of society — from politics and pop culture to history, sports and everything in between. This podcast makes ALL OF US part of the conversation — because we're all part of the story.", tag: "Podcast")

intersectionalityMatters = Interpret.create(name: "Intersectionality Matters! hosted by Kimberlé Crenshaw", image_url: "https://i.imgur.com/NhRj3JL.jpg", website_url: "https://aapf.org/podcast", description: "A podcast that brings intersectionality to life", tag: "Podcast")

momentum = Interpret.create(name: "Momentum: A Race Forward Podcast", image_url: "https://i.imgur.com/WW8M148.jpg", website_url: "https://www.raceforward.org/", description: "Momentum: A Race Forward Podcast features movement voices, stories, and strategies for racial justice. Co-hosts Chevon and Hiba give their unique takes on race and pop culture, and uplift narratives of hope, struggle, and joy, as we continue to build the momentum needed to advance racial justice in our policies, institutions, and culture. Build on your racial justice lens and get inspired to drive action by learning from organizational leaders and community activists.", tag: "Podcast")

stance = Interpret.create(name: "Stance", image_url: "https://i.imgur.com/tpDYruR.jpg", website_url: "https://stancepodcast.com/", description: "Chrystal Genesis[London] launched Stance in January 2017 as a transatlantic conversation covering arts and culture with San Francisco based Heta Fell.", tag: "Podcast")

theReceiptsPodcast = Interpret.create(name: "The Receipts Podcast", image_url: "https://i.imgur.com/Uvj5wUN.jpg", website_url: "https://play.acast.com/s/thereceipts#:~:text=by%20The%20Receipts%20Podcast%20%23TheReceiptsPodcast,girl%20talk%20with%20no%20filter.", description: "#TheReceiptsPodcast is a fun, honest podcast fronted by three girls who are willing to talk about anything and everything. From relationships to situationships to everyday life experiences, you can expect unadulterated girl talk with no filter.", tag: "Podcast")


p "#{Interpret.count} interpret(s) out of 7 podcasts created"


#############################################
#############################################
############# Interpret - Books  ############
#############################################
#############################################
stampedFromTheBeginning = Interpret.create(name: "Stamped From The Beginning - Ibram X. Kendi", image_url: "https://i.imgur.com/5Xn9nx7.jpg", website_url: "https://www.ibramxkendi.com/stamped-from-the-beginning", description: "In this deeply researched and fast-moving narrative, Kendi chronicles the entire story of anti-Black racist ideas and their staggering power over the course of American history. Stamped from the Beginning uses the life stories of five major American intellectuals to offer a window into the contentious debates between assimilationists and segregationists and between racists and antiracists. From Puritan minister Cotton Mather to Thomas Jefferson, from fiery abolitionist William Lloyd Garrison to brilliant scholar W.E.B. Du Bois to legendary anti-prison activist Angela Davis, Kendi shows how and why some of our leading proslavery and pro-civil rights thinkers have challenged or helped cement racist ideas in America.", tag: "Books")

aPeoplesHistoryOfTheUnitedStates = Interpret.create(name: "A People's History Of The United States - Howard Zinn", image_url: "https://i.imgur.com/XjDaMIW.jpg", website_url: "https://www.zinnedproject.org/materials/peoples-history-of-the-united-states", description: "Library Journal calls Howard Zinn’s A People’s History of the United States “a brilliant and moving history of the American people from the point of view of those...whose plight has been largely omitted from most histories.” Packed with vivid details and telling quotations, Zinn’s award-winning classic continues to revolutionize the way U.S. history is taught and remembered. -Zinned Education Project", tag: "Books")

whiteFragility = Interpret.create(name: "White Fragility: Why It’s So Hard For White People To Talk About Racism - Robin DiAngelo", image_url: "https://i.imgur.com/ZKf3oKH.jpg", website_url: "https://robindiangelo.com/publications/", description: "Racial stress results from an interruption to what is racially familiar. In turn, whites are often at a loss for how to respond in constructive ways., as we have not had to build the cognitive or affective skills or develop the stamina that that would allow for constructive engagement across racial divides. leading to what I refer to as White Fragility. White Fragility is a state in which even a minimum amount of racial stress becomes intolerable, triggering a range of defensive moves. These moves include the outward display of emotions such as anger, fear, and guilt, and behaviors such as argumentation, silence, and leaving the stress-inducing situation. These behaviors, in turn, function to reinstate white racial equilibrium. This book explicates the dynamics of White Fragility and how we might build our capacity in the on-going work towards racial justice.", tag: "Books")

soYouWantToTalkAboutRace = Interpret.create(name: "So You Want To Talk About Race - Ijeoma Oluo", image_url: "https://i.imgur.com/7XCtKeu.jpg", website_url: "http://www.ijeomaoluo.com/", description: "In So You Want to Talk About Race, Ijeoma Oluo guides readers of all races through subjects ranging from intersectionality and affirmative action to “model minorities” in an attempt to make the seemingly impossible possible: honest conversations about race and racism, and how they infect almost every aspect of American life. -Hachette Book Group", tag: "Books")

theBurningHouse = Interpret.create(name: "The Burning House: Jim Crow and the Making of Modern America - Anders Walker", image_url: "https://i.imgur.com/VsGNBZb.jpg", website_url: "https://www.slu.edu/law/faculty/anders-walker.php", description: "Anders Walker shows how a generation of scholars and judges has misinterpreted Powell’s definition of diversity in the landmark case Regents v. Bakke, forgetting its Southern origins and weakening it in the process. By resituating the decision in the context of Southern intellectual history, Walker places diversity on a new footing, independent of affirmative action but also free from the constraints currently placed on it by the Supreme Court. With great clarity and insight, he offers a new lens through which to understand the history of civil rights in the United States. -Yale Books", tag: "Books")

newJimCrow = Interpret.create(name: "The New Jim Crow - Michelle Alexander", image_url: "https://i.imgur.com/nLELjLC.jpg", website_url: "https://newjimcrow.com/about", description: "The New Jim Crow is a stunning account of the rebirth of a caste-like system in the United States, one that has resulted in millions of African Americans locked behind bars and then relegated to a permanent second-class status—denied the very rights supposedly won in the Civil Rights Movement. Alexander shows that, by targeting black men through the War on Drugs and decimating communities of color, the U.S. criminal justice system functions as a contemporary system of racial control, even as it formally adheres to the principle of colorblindness. The New Jim Crow challenges the civil rights community—and all of us—to place mass incarceration at the forefront of a new movement for racial justice in America.", tag: "Books")

theCondemnationOfBlackness = Interpret.create(name: "The Condemnation of Blackness: Race, Crime, and the Making of Modern Urban America - Khalil Gibran Muhammad", image_url: "https://i.imgur.com/ReIezMW.jpg", website_url: "https://www.hks.harvard.edu/faculty/khalil-muhammad", description: "The idea of black criminality was crucial to the making of modern urban America, as were African Americans’ own ideas about race and crime. Chronicling the emergence of deeply embedded notions of black people as a dangerous race of criminals by explicit contrast to working-class whites and European immigrants, Khalil Gibran Muhammad reveals the influence such ideas have had on urban development and social policies. -Harvard University Press", tag: "Books")

dyingOfWhiteness = Interpret.create(name: "Dying of Whiteness: How the Politics of Racial Resentment is Killing America's Heartland -  Jonathan M. Metzl", image_url: "https://i.imgur.com/AHRnzk3.jpg", website_url: "https://www.dyingofwhiteness.com/", description: "Physician and sociologist Jonathan M. Metzl travels across America's heartland seeking to better understand the politics of racial resentment and its impact on public health. Interviewing a range of Americans, he uncovers how racial anxieties led to the repeal of gun control laws in Missouri, stymied the Affordable Care Act in Tennessee, and fueled massive cuts to schools and social services in Kansas. Although such measures promised to restore greatness to white America, Metzl’s systematic analysis of health data dramatically reveals they did just the opposite: these policies made life sicker, harder, and shorter in the very populations they purported to aid.  Thus, white gun suicides soared, life expectancies fell, and school dropout rates rose. Powerful, searing, and sobering, Dying of Whiteness ultimately demonstrates just how much white America would benefit by emphasizing cooperation, rather than by chasing false promises of supremacy.", tag: "Books")

aDifferentMirror = Interpret.create(name: "A Different Mirror: A History of Multicultural America - Ronald Takaki", image_url: "https://i.imgur.com/pyC8a2a.jpg", website_url: "https://www.zinnedproject.org/materials/different-mirror-multicultural-america", description: "Upon its first publication, A Different Mirror was hailed by critics and academics everywhere as a dramatic new retelling of our nation’s past. Beginning with the colonization of the New World, it recounted the history of America in the voice of the non-Anglo peoples of the United States–Native Americans, African Americans, Jews, Irish Americans, Asian Americans, Latinos, and others–groups who helped create this country’s rich mosaic culture. [The current 2008] edition of A Different Mirror is a remarkable achievement that grapples with the raw truth of American history and examines the ultimate question of what it means to be an American.” -Hachette Book Group", tag: "Books")

howToBeAnAntiracist = Interpret.create(name: "How To Be An Antiracist - Ibram X. Kendi", image_url: "https://i.imgur.com/xd32lyV.jpg", website_url: "https://www.ibramxkendi.com/how-to-be-an-antiracist-1", description: "Ibram X. Kendi's concept of antiracism reenergizes and reshapes the conversation about racial justice in America--but even more fundamentally, points us toward liberating new ways of thinking about ourselves and each other. Instead of working with the policies and system we have in place, Kendi asks us to think about what an antiracist society might look like, and how we can play an active role in building it.", tag: "Books")

evicted = Interpret.create(name: "Evicted: Poverty and Profit in the American City - Matthew Desmond", image_url: "https://i.imgur.com/TXgEG2Q.jpg", website_url: "https://www.evictedbook.com/", description: "In Evicted, Princeton sociologist and MacArthur “Genius” Matthew Desmond follows eight families in Milwaukee as they each struggle to keep a roof over their heads. Hailed as “wrenching and revelatory” (The Nation), “vivid and unsettling” (New York Review of Books), Evicted transforms our understanding of poverty and economic exploitation while providing fresh ideas for solving one of twenty-first-century America’s most devastating problems. Its unforgettable scenes of hope and loss remind us of the centrality of home, without which nothing else is possible.", tag: "Books")

nobody = Interpret.create(name: "Nobody: Casualties of America’s War on the Vulnerable, From Ferguson to Flint and Beyond - Marc Lamont Hill", image_url: "https://i.imgur.com/tsJQRiq.jpg", website_url: "http://www.marclamonthill.com/", description: "Marc Lamont Hill carefully considers a string of high-profile deaths in America—Sandra Bland, Freddie Gray, Michael Brown, Eric Garner, Trayvon Martin, and others—and incidents of gross negligence by government, such as the water crisis in Flint, Michigan. He digs underneath these events to uncover patterns and policies of authority that allow some citizens become disempowered, disenfranchised, poor, uneducated, exploited, vulnerable, and disposable. To help us understand the plight of vulnerable communities, he examines the effects of unfettered capitalism, mass incarceration, and political power while urging us to consider a new world in which everyone has a chance to become somebody. Heralded as an essential text for our times, Marc Lamont Hill’s galvanizing work embodies the best traditions of scholarship, journalism, and storytelling to lift unheard voices and to address the necessary question, 'how did we get here?' -greaterdiversity.com", tag: "Books")

liesMyTeacherToldMe = Interpret.create(name: "Lies My Teacher Told Me: Everything Your American History Textbook Got Wrong - James W. Loewen", image_url: "https://i.imgur.com/mJfHqfr.jpg", website_url: "https://sundown.tougaloo.edu/", description: "What started out as a survey of the twelve leading American history textbooks has ended up being what the San Francisco Chronicle calls 'an extremely convincing plea for truth in education.' In Lies My Teacher Told Me, James W. Loewen brings history alive in all its complexity and ambiguity. Beginning with pre-Columbian history and ranging over characters and events as diverse as Reconstruction, Helen Keller, the first Thanksgiving, the My Lai massacre, 9/11, and the Iraq War, Loewen offers an eye-opening critique of existing textbooks, and a wonderful retelling of American history as it should — and could — be taught to American students. -Zinned Education Project", tag: "Books")

whyAreAllTheBlackKidsSittingTogetherInTheCafeteria = Interpret.create(name: "Why Are All The Black Kids Sitting Together In The Cafeteria? And Other Conversations About Race - Beverly Daniel Tatum", image_url: "https://i.imgur.com/teL7s2p.jpg", website_url: "https://www.spelman.edu/about-us/office-of-the-president/past-presidents/beverly-daniel-tatum", description: "In 1997, Beverly Daniel Tatum, one of the country’s foremost authorities on the psychology of racism, answered a recurring question that surfaced in her work with teachers, administrators, and parent groups: Why are all the black kids sitting together in the cafeteria? The result was a critically acclaimed book of the same name that gave readers—numbering in the hundreds of thousands—a starting point to demystify conversations about race, better understand the concept of racial identity, and communicate across racial and ethnic divides. -The Atlantic", tag: "Books")

theColorOfLaw = Interpret.create(name: "The Color of Law: A Forgotten History of How Our Government Segregated America - Richard Rothstein", image_url: "https://i.imgur.com/dselWia.jpg", website_url: "https://www.epi.org/people/richard-rothstein/", description: "Richard Rothstein explodes the myth that America's cities came to be racially divided through de facto segregation--that is, through individual prejudices, income differences, or the actions of private institutions like banks and real estate agencies. Rather, The Color of Law incontrovertibly makes it clear that it was de jure segregation--the laws and policy decisions passed by local, state, and federal governments--that actually promoted the discriminatory patterns that continue to this day. -Jacket", tag: "Books")

blackballed = Interpret.create(name: "Blackballed: The Black Vote and US Democracy - Darryl Pinckney", image_url: "https://i.imgur.com/ozHH24Y.jpg", website_url: "http://darrylpinckney.com/", description: "Blackballed is Darryl Pinckney's meditation on a century and a half of Black participation in U.S. electoral politics. In this combination of memoir, historical narrative, and contemporary political and social analysis, he investigates the struggle for Black voting rights from Reconstruction through the civil rights movement, leading up to the election of Barack Obama as president. Interspersed throughout the historical narrative are Pinckney's own memories of growing up during the Civil Rights Era, his unsure grasp of the events he saw on television or heard discussed, and the reactions of his parents to the social changes that were taking place at the time and later to Obama's election. He concludes with an examination of the current state of electoral politics, the place of Blacks in the Democratic coalition, and the ongoing efforts by Republicans to suppress the Black vote, with particular attention to the Supreme Court's recent decision to strike down part of the Voting Rights Act of 1965 and what it may mean for the political influence of Black voters in future elections. -Worldcat", tag: "Books")



p "#{Interpret.count} interpret(s) out of 16 books created"

#############################################
#############################################
############# Interpret - Media  ############
#############################################
#############################################

thirteenth = Interpret.create(name: "13th, 2016", image_url: "https://i.imgur.com/Kr1X39o.jpg", website_url: "https://www.netflix.com/title/80091741", description: "In this thought-provoking documentary, scholars, activists and politicians analyze the criminalization of African Americans and the U.S. prison boom.", tag: "Movies")

americanSon = Interpret.create(name: "American Son, 2019", image_url: "https://i.imgur.com/FK9UYwT.jpg", website_url: "https://www.netflix.com/title/81024100", description: "Time passes and tension mounts in a Florida police station as an estranged interracial couple awaits news of their missing teenage son.", tag: "Movies")

dearWhitePeople = Interpret.create(name: "Dear White People, 2017", image_url: "https://i.imgur.com/uZnQCf6.jpg", website_url: "https://www.netflix.com/title/80095698", description: "Students of color navigate the daily slights and slippery politics of life at an Ivy League college that's not nearly as 'post-racial' as it thinks.", tag: "Movies")

seeYouYesterday = Interpret.create(name: "See You Yesterday, 2019", image_url: "https://i.imgur.com/K2OzSQl.jpg", website_url: "https://www.netflix.com/title/80216758", description: "As two teen prodigies try to master the art of time travel, a tragic police shooting sends them on a series of dangerous trips to the past.", tag: "Movies")

theHelp = Interpret.create(name: "The Help, 2011", image_url: "https://i.imgur.com/Sxss92i.jpg", website_url: "https://www.imdb.com/title/tt1454029/", description: "An aspiring author during the civil rights movement of the 1960s decides to write a book detailing the African American maids' point of view on the white families for which they work, and the hardships they go through on a daily basis. -IMDB", tag: "Movies")

getOut = Interpret.create(name: "Get Out, 2017", image_url: "https://i.imgur.com/CgtGp5Q.jpg", website_url: "https://www.imdb.com/title/tt5052448/", description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point. -IMDB", tag: "Movies")

mississippiBurning = Interpret.create(name: "Mississippi Burning, 1988", image_url: "https://i.imgur.com/TcXqKHx.jpg", website_url: "https://en.wikipedia.org/wiki/Mississippi_Burning", description: "Two F.B.I. Agents with wildly different styles arrive in Mississippi to investigate the disappearance of some civil rights activists. -IMDB", tag: "Movies")

whenTheySeeUs = Interpret.create(name: "When They See Us, 2019", image_url: "https://i.imgur.com/Zzn7mTB.jpg", website_url: "https://www.netflix.com/title/80200549", description: "Five teens from Harlem become trapped in a nightmare when they're falsely accused of a brutal attack in Central Park. Based on the true story.", tag: "Movies")

moonlight = Interpret.create(name: "Moonlight, 2016", image_url: "https://i.imgur.com/y92tR18.jpg", website_url: "https://www.imdb.com/title/tt4975722/", description: "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood. -IMDB", tag: "Movies")

theHateUGive = Interpret.create(name: "The Hate U Give, 2018", image_url: "https://i.imgur.com/LZB5Krp.jpg", website_url: "https://www.imdb.com/title/tt5580266/", description: "Starr witnesses the fatal shooting of her childhood best friend Khalil at the hands of a police officer. Now, facing pressure from all sides of the community, Starr must find her voice and stand up for what's right. -IMDB", tag: "Movies")

dope = Interpret.create(name: "Dope, 2015", image_url: "https://i.imgur.com/pYi0Rti.jpg", website_url: "https://www.imdb.com/title/tt3850214/", description: "A critical hit and audience favorite out of the Sundance Film Festival, in DOPE, Malcolm (Shameik Moore) is carefully surviving life in a tough neighborhood in Los Angeles while juggling college applications, academic interviews, and the SAT. A chance invitation to an underground party leads him into an adventure that could allow him to go from being a geek, to being dope, to ultimately being himself. -Rotten Tomatoes", tag: "Movies")

theColorPurple = Interpret.create(name: "The Color Purple, 1985", image_url: "https://i.imgur.com/3dO3wBx.jpg", website_url: "https://www.imdb.com/title/tt0088939/", description: "A black Southern woman struggles to find her identity after suffering abuse from her father and others over four decades. -IMDB", tag: "Movies")

blackPanter = Interpret.create(name: "Black Panter, 2018", image_url: "https://i.imgur.com/tFVsqTS.jpg", website_url: "https://www.imdb.com/title/tt1825683/", description: "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past. -IMDB", tag: "Movies")

selma = Interpret.create(name: "Selma, 2014", image_url: "https://i.imgur.com/nPRnrBu.jpg", website_url: "https://www.imdb.com/title/tt1020072/", description: "A chronicle of Dr. Martin Luther King, Jr.'s campaign to secure equal voting rights via an epic march from Selma to Montgomery, Alabama, in 1965. -IMDB", tag: "Movies")

justMercy = Interpret.create(name: "Just Mercy, 2019", image_url: "https://i.imgur.com/tULiUmn.jpg", website_url: "https://www.justmercyfilm.com/", description: "Just Mercy is based on the powerful and thought-provoking true story of young lawyer Bryan Stevenson and his history-making battle for justice. After graduating from Harvard, Bryan had his pick of lucrative jobs. Instead, he heads to Alabama to defend those wrongly condemned or who were not afforded proper representation, with the support of local advocate Eva Ansley. One of his first, and most incendiary, cases is that of Walter McMillian, who, in 1987, was sentenced to die for the notorious murder of an 18-year-old girl, despite a preponderance of evidence proving his innocence and the fact that the main testimony against him came from a criminal with a motive to lie. In the years that follow, Bryan becomes embroiled in a labyrinth of legal and political maneuverings, as well as overt and unabashed racism as he fights for Walter, and others like him, with the odds—and the system—stacked against them.", tag: "Movies")

p "#{Interpret.count} interpret(s) out of 15 movies created"

p "#{Interpret.count} interpret(s) out of 66 total created"
# Food/Beauty/Podcasts/Fashion/Tech/Media: Story, Mission Statement and/or About descriptions, taken directly from company’s website unless otherwise noted.
# Books: Descriptions taken directly from Author's website unless otherwise noted.

# = Interpret.create(name: "", image_url: "", website_url: "", description: "", tag: "")
# = Dream.create(location: "", year: "", story: "")